### ISSUE TITLE
rufus-7 v4.5 (hotfix) crashing upon launch for unknown reasons.

### ISSUE THREAD

**Issue by TainaShiro** [Smu1zel/rufus-7#2]
﻿Checklist
---------
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the full log, starting with the line `Rufus version: x.y.z` - No part of it has been removed.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus 7 on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
[
![Clipboard_07-09-2024_rufus4_5crash](https://github.com/Smu1zel/rufus-7/assets/115933380/4e8877a8-c55e-40cf-8972-14326d67317e)
](url)
But version 4.4 working just fine:
![image](https://github.com/Smu1zel/rufus-7/assets/115933380/df2ab045-4a6e-46c8-b010-b0669b8bb740)

Log (if applicable)
---
```
<FULL LOG>
```

**Comment by Smu1zel** [comment]
Could you try v4.6? v4.5 wasn't tested very well, and I rushed the hotfix.

**Comment by TainaShiro** [comment]
Sure!
Unfortunately the same crash still occurs on startup :/. Here the image on my physical machine:
![Clipboard_08-10-2024_01](https://github.com/user-attachments/assets/538668d4-6b45-4870-8278-604df6ed2fa8)

Strangely the crash did not happen when I ran v4.6 on a Windows 7 virtual machine inside a physical Windows 10 LTSC 2021 machine.

But I do have some ideas why it might crash through other software's developers release note/insights:
![Untitled-2](https://github.com/user-attachments/assets/345d29a8-8e95-4c44-bd2e-0fbe273640bd)

**Comment by Smu1zel** [comment]
> Sure! Unfortunately the same crash still occurs on startup :/. Here the image on my physical machine: ![Clipboard_08-10-2024_01](https://private-user-images.githubusercontent.com/115933380/356689972-538668d4-6b45-4870-8278-604df6ed2fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MzQ3NzcsIm5iZiI6MTcyNDUzNDQ3NywicGF0aCI6Ii8xMTU5MzMzODAvMzU2Njg5OTcyLTUzODY2OGQ0LTZiNDUtNDg3MC04Mjc4LTYwNGRmNmVkMmZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQyMTIxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTE0MGI0NjllZmUwYTQyOTM4ODlhNWJjZjAxMDMzOTM5NTgwZDVkZDkyNDY1YWM4ZmY0Yzc2YjY3MGY3MzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rSMWi1QM-ql5MqPpjnLjTkH1bcXY4YLA8xSd4KQz_A)
> 
> Strangely the crash did not happen when I ran v4.6 on a Windows 7 virtual machine inside a physical Windows 10 LTSC 2021 machine.
> 
> But I do have some ideas why it might crash through other software's developers release note/insights: ![Untitled-2](https://private-user-images.githubusercontent.com/115933380/356692557-345d29a8-8e95-4c44-bd2e-0fbe273640bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MzQ3NzcsIm5iZiI6MTcyNDUzNDQ3NywicGF0aCI6Ii8xMTU5MzMzODAvMzU2NjkyNTU3LTM0NWQyOWE4LThlOTUtNGM0NC1iZDJlLTBmYmUyNzM2NDBiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQyMTIxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWRiZmY4Y2FlY2RjMjU3NWRlY2ViOWNlODBhZGNkNGU1MzQ3OGQ2NTg1ZGFkMzBjODU1OGJmZTY1OGQ4NTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TkI22JZx055qFPWGgcyr3yZQphfwozBRyP-XAUjwbZY)

What CPU are you using with your Windows 10 system, and what CPU are you using with the system it doesn't work on? Does the x86 32-bit build work on the latter?

**Comment by TainaShiro** [comment]
I use an Intel i5-3340M CPU on Windows 10 system, also an Intel i5-3340M CPU on Windows 7. Basically it is the same device (a Dell Latitude E5430 laptop), I just downgrade to Windows 7 or upgrade to Windows 10 from time to time. And no, the 32-bit build does not work neither.

**Comment by bt4ibwem8** [comment]
I also have this error. Besides the "stopped working" error I get first this error:

![image](https://github.com/user-attachments/assets/5ed299a9-d301-40f0-a1cd-043f88b07e02)

4.5 and 4.6 versions do not work for me, but 4.4 works...

**Comment by Smu1zel** [comment]
> I also have this error. Besides the "stopped working" error I get first this error:
> 
> ![image](https://private-user-images.githubusercontent.com/114884026/365391564-5ed299a9-d301-40f0-a1cd-043f88b07e02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDA5MDQsIm5iZiI6MTcyNTc0MDYwNCwicGF0aCI6Ii8xMTQ4ODQwMjYvMzY1MzkxNTY0LTVlZDI5OWE5LWQzMDEtNDBmMC1hMWNkLTA0M2Y4OGIwN2UwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QyMDIzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjQ3YWNiMDIxNmYwYjliYjg0MjhiOTBmNDU2YTdhZDQyNTk3OTMyNGU4ODU0MWNhMWU3NWNhNWNhNDEwZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eKuE5QXGZI3h7bxPqchKpiShuuVdcg3WZYD_Nub55HE)
> 
> 4.5 and 4.6 versions do not work for me, but 4.4 works...

iirc, the only special thing about 4.4 was I built it with another PC since the charger for my main one was broken.

Does 4.3 work even?

**Comment by bt4ibwem8** [comment]
4.3 works

**Comment by Smu1zel** [comment]
> 4.3 works

What ISO are you using? What changes have you made since then?

I'm asking, since I've tried multiple Windows 7 installs (including one on a 32-bit Pentium 4) and I still can't reproduce this.

If you're able, I'd try and bisect the problem (git feature). For reference, 4.0 to 4.5 were built on Windows 11 with VS 2022, and 4.6 and up use MSYS2 MinGW. It should be possible to build this on Windows 7 with at least one of them, but I don't do that.

**Comment by bt4ibwem8** [comment]
I did not use ISO, i just opened 4.3 .exe file and Rufus ran fine...

**Comment by Smu1zel** [comment]
> I did not use ISO, i just opened 4.3 .exe file and Rufus ran fine...

I'm asking what Windows 7 ISO you used. If I can actually reproduce the problem, then I can fix it. Much harder to do so if I can't.

**Comment by bt4ibwem8** [comment]
I used ISO from gen2. You can download it over torrent. But i also applied all ESU updates (for Windows Server 2008 R2) and i did some changes in system which i do not remember exactly, so maybe there is problem in my system. I assume it would work if i clean install win7. Maybe i can try in Virtualbox...

**Comment by Smu1zel** [comment]
Turns out this is all my fault. I somehow neglected testing the **main function** of the app on Windows 7, and only tested the UI stuff.

Sorry for all the trouble. I promise I'll try to fix this tomorrow.

**Comment by Smu1zel** [comment]
I've made a new release. Does it work for everyone now?

**Comment by bt4ibwem8** [comment]
it works for me

**Comment by TainaShiro** [comment]
![Clipboard_11-27-2024_01](https://github.com/user-attachments/assets/d5c702e1-93fa-4008-bc6b-cafc5fc388af)
Just tested the x86 version on a 32-bit VM, it is working fine!
